twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    ## FORM THEMES
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - '@SonataCore/Form/color.html.twig'                