sonata_admin:
    title: 'Sonata Admin'
    title_logo: bundles/sonataadmin/logo_title.png

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }    
        # SONATA MENU 
        groups:     
            # Optional for symfony 4
            # sonata.admin.group.menu_builder:
            #    label:           config.label_menu
            #    label_catalogue: ProdigiousSonataMenuBundle
            #    icon:            '<i class="fa fa-magic"></i>'
            #    items:
            #        - prodigious_sonata_menu.admin.menu

            # Sonata page menu
            #sonata.admin.group.site_builder:
            #    label:           site
            #    label_catalogue: SonataPageBundle
            #    icon:            '<i class="fa fa-puzzle-piece"></i>'
            #    items:
            #        - sonata.page.admin.site
            #        - sonata.page.admin.page
        
    templates:
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'

    security:
        handler: app.security.handler.voter

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN        